theme: minima
rss: rss
title: Infra Blog
show_excerpts: true
kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      psth: ""
      type: posts
    values:
      tags: Other
